### ISSUE TITLE
Unable to run default benchmark with Python 3.9

### ISSUE THREAD

**Issue by psteinb** [sbi-benchmark/results#2]
After following the installation instructions, I seem to be unable to run anything:

```
sbibm/results/benchmarking_sbi $ python ./run.py                                              
/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/core/plugins.py:202: UserWarning: 
	Error importing 'hydra._internal.core_plugins.importlib_resources_config_source'.
	Plugin is incompatible with this Hydra version or buggy.
	Recommended to uninstall or upgrade plugin.
		ModuleNotFoundError : No module named 'importlib_resources'
  warnings.warn(
/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/core/plugins.py:202: UserWarning: 
	Error importing 'hydra_plugins.hydra_joblib_launcher.joblib_launcher'.
	Plugin is incompatible with this Hydra version or buggy.
	Recommended to uninstall or upgrade plugin.
		ImportError : cannot import name 'HydraContext' from 'hydra.types' (/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/types.py)
  warnings.warn(
/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/core/plugins.py:202: UserWarning: 
	Error importing 'hydra_plugins.hydra_rq_launcher.rq_launcher'.
	Plugin is incompatible with this Hydra version or buggy.
	Recommended to uninstall or upgrade plugin.
		ImportError : cannot import name 'HydraContext' from 'hydra.types' (/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/types.py)
  warnings.warn(
Traceback (most recent call last):
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/utils.py", line 320, in <lambda>
    lambda: Hydra.create_main_hydra2(
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/hydra.py", line 73, in create_main_hydra2
    config_loader: ConfigLoader = ConfigLoaderImpl(
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 79, in __init__
    self.repository: ConfigRepository = ConfigRepository(
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/config_repository.py", line 22, in __init__
    source_type = SourcesRegistry.instance().resolve(scheme)
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/sources_registry.py", line 29, in resolve
    raise ValueError(
ValueError: No config source registered for schema pkg, supported types : [file, structured]
```

Is there anything I can check or do?

**Comment by jan-matthis** [comment]
Thanks for reporting this! There seems to be a problem with Hydra, more specifically, the plugins I wrote for it. Could you check which versions of the following packages are installed: `hydra-core`, `hydra-joblib-launcher`, `hydra-rq-launcher`?

My suspicion is that we the incompatibility with hydra plugins is due to the [`>=` requirement here](https://github.com/sbi-benchmark/results/blob/main/benchmarking_sbi/requirements.txt#L5-L6), i.e., we might need to pin them to a lower version, or update the API.

**Comment by psteinb** [comment]
```
$ python -m pip show hydra-core                             
Name: hydra-core
Version: 1.0.3
Summary: A framework for elegantly configuring complex applications
Home-page: https://github.com/facebookresearch/hydra
Author: Omry Yadan
Author-email: omry@fb.com
License: UNKNOWN
Location: /home/steinbac/development/sbibm/results/sbibm-results-venv/lib/python3.9/site-packages
Requires: omegaconf, antlr4-python3-runtime
Required-by: hydra-rq-launcher, hydra-joblib-launcher
$ python -m pip show hydra-joblib-launcher    
Name: hydra-joblib-launcher
Version: 1.1.5
Summary: Joblib Launcher for Hydra apps
Home-page: https://github.com/facebookresearch/hydra/
Author: Jan-Matthis Lueckmann, Omry Yadan
Author-email: mail@jan-matthis.de, omry@fb.com
License: UNKNOWN
Location: /home/steinbac/development/sbibm/results/sbibm-results-venv/lib/python3.9/site-packages
Requires: hydra-core, joblib
$ python -m pip show hydra-rq-launcher    
Name: hydra-rq-launcher
Version: 1.1.0
Summary: Redis Queue (RQ) Launcher for Hydra apps
Home-page: https://github.com/facebookresearch/hydra/
Author: Jan-Matthis Lueckmann, Omry Yadan
Author-email: mail@jan-matthis.de, omry@fb.com
License: UNKNOWN
Location: /home/steinbac/development/sbibm/results/sbibm-results-venv/lib/python3.9/site-packages
Requires: fakeredis, cloudpickle, rq, hydra-core
Required-by:
```

**Comment by psteinb** [comment]
I downgraded as 
```
$  python -m pip install hydra-rq-launcher==1.0.1
$  python -m pip install hydra-joblib-launcher==1.1.0
$  python -m pip install hydra-core==1.0.3 #just to easy my paranoia ;-)
```
But the error prevails:
```
$ cd benchmarking_sbi
$ python ./run.py --help              
/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/core/plugins.py:202: UserWarning: 
	Error importing 'hydra._internal.core_plugins.importlib_resources_config_source'.
	Plugin is incompatible with this Hydra version or buggy.
	Recommended to uninstall or upgrade plugin.
		ModuleNotFoundError : No module named 'importlib_resources'
  warnings.warn(
Traceback (most recent call last):
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/utils.py", line 320, in <lambda>
    lambda: Hydra.create_main_hydra2(
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/hydra.py", line 73, in create_main_hydra2
    config_loader: ConfigLoader = ConfigLoaderImpl(
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 79, in __init__
    self.repository: ConfigRepository = ConfigRepository(
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/config_repository.py", line 22, in __init__
    source_type = SourcesRegistry.instance().resolve(scheme)
  File "/home/steinbac/development/sbibm/results/sbibm-results-venv/lib64/python3.9/site-packages/hydra/_internal/sources_registry.py", line 29, in resolve
    raise ValueError(
ValueError: No config source registered for schema pkg, supported types : [file, structured]
```
However, the error messages for the plugins have dissappeared.

**Comment by psteinb** [comment]
[This](https://hydra.cc/docs/intro#versions) suggests, that this error mostly stems from the main hydra version not being compatible with python `3.9` (which I happen to be running). See #3

**Comment by jan-matthis** [comment]
I'm currently investigating what we would need to change for Python 3.9 across all packages that the benchmark uses. 

In the meantime, can you know confirm whether things work as they should with Python 3.8 and the downgraded Hydra plugins?

**Comment by psteinb** [comment]
It might be worth considering a github-actions based check of such things using a python version matrix.

Just tried with python 3.8.12 (admittedly quite recent), but the current state of affairs wrt to hydra works like a charm.
